---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: fancy-supply-chain
spec:
  resources:
  - name: git-source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: git-source-template
  - name: image-builder
    templateRef:
      kind: ClusterImageTemplate
      name: kpack-build
    sources:
    - resource: git-source-provider
      name: source
  serviceAccountRef:
    name: workload
    namespace: default
  selector:
    workload-type: from-git
  