---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload
subjects:
  - kind: ServiceAccount
    name: workload
